// File: lib/quranData.js

export const reciterList = [
  {
    header: "",
    title: "ناصر القطامي",
    description: "",
    id: "Nasser_Alqatami_128kbps",
    image: "https://i.ibb.co/dWv5VCb/naser.webp",
  },
  {
    header: "",
    title: "ياسر الدوسري",
    description: "",
    id: "Yasser_Ad-Dussary_128kbps",
    image: "https://i.ibb.co/h7yr645/daousari.webp",
  },
  {
    header: "",
    title: "عبد الرحمان السديس",
    description: "",
    id: `Abdurrahmaan_As-Sudais_192kbps`,
    image: "https://i.ibb.co/Rc70gn7/sudais.webp",
  },
  {
    header: "",
    title: "مشاري راشد العفاسي",
    description: "",
    id: `Alafasy_128kbps`,
    image: "https://i.ibb.co/gJK0xJL/afasy.jpg",
  },
  {
    header: "",
    title: "ماهر المعيقلي",
    description: "",
    id: "MaherAlMuaiqly128kbps",
    image: "https://i.ibb.co/r6mP02n/maher.jpg",
  },
  {
    header: "",
    title: "عبد الباسط عبد الصمد",
    description: "",
    id: "Abdul_Basit_Mujawwad_128kbps",
    image: "https://i.ibb.co/b3WcpjC/abdelbaset.jpg",
  },
  {
    header: "",
    title: "أحمد ابن علي العجمي",
    description: "",
    id: "Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net",
    image: "https://i.ibb.co/9tHB5jN/images.jpg",
  },
  {
    header: "",
    title: "أكرم العلاقمي",
    description: "",
    id: "Akram_AlAlaqimy_128kbps",
    image: "https://i.ibb.co/f960x7b/Untitled.jpg",
  },
  {
    header: "",
    title: "سعد الغامدي",
    description: "",
    id: "Ghamadi_40kbps",
    image: "https://i.ibb.co/vLbQ0gs/ghamidi.jpg",
  },
];

export const surahList = [
  {
    header: "",
    title: "1- الفاتحة",
    description: "",
    id: "001",
  },
  {
    header: "",
    title: "2- البقرة",
    description: "",
    id: "002",
  },
  {
    header: "",
    title: "3- آل عمران",
    description: "",
    id: "003",
  },
  {
    header: "",
    title: "4- النساء",
    description: "",
    id: "004",
  },
  {
    header: "",
    title: "5- المائدة",
    description: "",
    id: "005",
  },
  {
    header: "",
    title: "6- الأنعام",
    description: "",
    id: "006",
  },
  {
    header: "",
    title: "7- الأعراف",
    description: "",
    id: "007",
  },
  {
    header: "",
    title: "8- الأنفال",
    description: "",
    id: "008",
  },
  {
    header: "",
    title: "9- التوبة",
    description: "",
    id: "009",
  },
  {
    header: "",
    title: "10- يونس",
    description: "",
    id: "010",
  },
  {
    header: "",
    title: "11- هود",
    description: "",
    id: "011",
  },
  {
    header: "",
    title: "12- يوسف",
    description: "",
    id: "012",
  },
  {
    header: "",
    title: "13- الرعد",
    description: "",
    id: "013",
  },
  {
    header: "",
    title: "14- إبراهيم",
    description: "",
    id: "014",
  },
  {
    header: "",
    title: "15- الحجر",
    description: "",
    id: "015",
  },
  {
    header: "",
    title: "16- النحل",
    description: "",
    id: "016",
  },
  {
    header: "",
    title: "17- الإسراء",
    description: "",
    id: "017",
  },
  {
    header: "",
    title: "18- الكهف",
    description: "",
    id: "018",
  },
  {
    header: "",
    title: "19- مريم",
    description: "",
    id: "019",
  },
  {
    header: "",
    title: "20- طه",
    description: "",
    id: "020",
  },
  {
    header: "",
    title: "21- الأنبياء",
    description: "",
    id: "021",
  },
  {
    header: "",
    title: "22- الحج",
    description: "",
    id: "022",
  },
  {
    header: "",
    title: "23- المؤمنون",
    description: "",
    id: "023",
  },
  {
    header: "",
    title: "24- النور",
    description: "",
    id: "024",
  },
  {
    header: "",
    title: "25- الفرقان",
    description: "",
    id: "025",
  },
  {
    header: "",
    title: "26- الشعراء",
    description: "",
    id: "026",
  },
  {
    header: "",
    title: "27- النمل",
    description: "",
    id: "027",
  },
  {
    header: "",
    title: "28- القصص",
    description: "",
    id: "028",
  },
  {
    header: "",
    title: "29- العنكبوت",
    description: "",
    id: "029",
  },
  {
    header: "",
    title: "30- الروم",
    description: "",
    id: "030",
  },
  {
    header: "",
    title: "31- لقمان",
    description: "",
    id: "031",
  },
  {
    header: "",
    title: "32- السجدة",
    description: "",
    id: "032",
  },
  {
    header: "",
    title: "33- الأحزاب",
    description: "",
    id: "033",
  },
  {
    header: "",
    title: "34- سبأ",
    description: "",
    id: "034",
  },
  {
    header: "",
    title: "35- فاطر",
    description: "",
    id: "035",
  },
  {
    header: "",
    title: "36- يس",
    description: "",
    id: "036",
  },
  {
    header: "",
    title: "37- الصافات",
    description: "",
    id: "037",
  },
  {
    header: "",
    title: "38- ص",
    description: "",
    id: "038",
  },
  {
    header: "",
    title: "39- الزمر",
    description: "",
    id: "039",
  },
  {
    header: "",
    title: "40- غافر",
    description: "",
    id: "040",
  },
  {
    header: "",
    title: "41- فصلت",
    description: "",
    id: "041",
  },
  {
    header: "",
    title: "42- الشورى",
    description: "",
    id: "042",
  },
  {
    header: "",
    title: "43- الزخرف",
    description: "",
    id: "043",
  },
  {
    header: "",
    title: "44- الدخان",
    description: "",
    id: "044",
  },
  {
    header: "",
    title: "45- الجاثية",
    description: "",
    id: "045",
  },
  {
    header: "",
    title: "46- الأحقاف",
    description: "",
    id: "046",
  },
  {
    header: "",
    title: "47- محمد",
    description: "",
    id: "047",
  },
  {
    header: "",
    title: "48- الفتح",
    description: "",
    id: "048",
  },
  {
    header: "",
    title: "49- الحجرات",
    description: "",
    id: "049",
  },
  {
    header: "",
    title: "50- ق",
    description: "",
    id: "050",
  },
  {
    header: "",
    title: "51- الذاريات",
    description: "",
    id: "051",
  },
  {
    header: "",
    title: "52- الطور",
    description: "",
    id: "052",
  },
  {
    header: "",
    title: "53- النجم",
    description: "",
    id: "053",
  },
  {
    header: "",
    title: "54- القمر",
    description: "",
    id: "054",
  },
  {
    header: "",
    title: "55- الرحمن",
    description: "",
    id: "055",
  },
  {
    header: "",
    title: "56- الواقعة",
    description: "",
    id: "056",
  },
  {
    header: "",
    title: "57- الحديد",
    description: "",
    id: "057",
  },
  {
    header: "",
    title: "58- المجادلة",
    description: "",
    id: "058",
  },
  {
    header: "",
    title: "59- الحشر",
    description: "",
    id: "059",
  },
  {
    header: "",
    title: "60- الممتحنة",
    description: "",
    id: "060",
  },
  {
    header: "",
    title: "61- الصف",
    description: "",
    id: "061",
  },
  {
    header: "",
    title: "62- الجمعة",
    description: "",
    id: "062",
  },
  {
    header: "",
    title: "63- المنافقون",
    description: "",
    id: "063",
  },
  {
    header: "",
    title: "64- التغابن",
    description: "",
    id: "064",
  },
  {
    header: "",
    title: "65- الطلاق",
    description: "",
    id: "065",
  },
  {
    header: "",
    title: "66- التحريم",
    description: "",
    id: "066",
  },
  {
    header: "",
    title: "67- الملك",
    description: "",
    id: "067",
  },
  {
    header: "",
    title: "68- القلم",
    description: "",
    id: "068",
  },
  {
    header: "",
    title: "69- الحاقة",
    description: "",
    id: "069",
  },
  {
    header: "",
    title: "70- المعارج",
    description: "",
    id: "070",
  },
  {
    header: "",
    title: "71- نوح",
    description: "",
    id: "071",
  },
  {
    header: "",
    title: "72- الجن",
    description: "",
    id: "072",
  },
  {
    header: "",
    title: "73- المزمل",
    description: "",
    id: "073",
  },
  {
    header: "",
    title: "74- المدثر",
    description: "",
    id: "074",
  },
  {
    header: "",
    title: "75- القيامة",
    description: "",
    id: "075",
  },
  {
    header: "",
    title: "76- الإنسان",
    description: "",
    id: "076",
  },
  {
    header: "",
    title: "77- المرسلات",
    description: "",
    id: "077",
  },
  {
    header: "",
    title: "78- النبأ",
    description: "",
    id: "078",
  },
  {
    header: "",
    title: "79- النازعات",
    description: "",
    id: "079",
  },
  {
    header: "",
    title: "80- عبس",
    description: "",
    id: "080",
  },
  {
    header: "",
    title: "81- التكوير",
    description: "",
    id: "081",
  },
  {
    header: "",
    title: "82- الانفطار",
    description: "",
    id: "082",
  },
  {
    header: "",
    title: "83- المطففين",
    description: "",
    id: "083",
  },
  {
    header: "",
    title: "84- الانشقاق",
    description: "",
    id: "084",
  },
  {
    header: "",
    title: "85- البروج",
    description: "",
    id: "085",
  },
  {
    header: "",
    title: "86- الطارق",
    description: "",
    id: "086",
  },
  {
    header: "",
    title: "87- الأعلى",
    description: "",
    id: "087",
  },
  {
    header: "",
    title: "88- الغاشية",
    description: "",
    id: "088",
  },
  {
    header: "",
    title: "89- الفجر",
    description: "",
    id: "089",
  },
  {
    header: "",
    title: "90- البلد",
    description: "",
    id: "090",
  },
  {
    header: "",
    title: "91- الشمس",
    description: "",
    id: "091",
  },
  {
    header: "",
    title: "92- الليل",
    description: "",
    id: "092",
  },
  {
    header: "",
    title: "93- الضحى",
    description: "",
    id: "093",
  },
  {
    header: "",
    title: "94- الشرح",
    description: "",
    id: "094",
  },
  {
    header: "",
    title: "95- التين",
    description: "",
    id: "095",
  },
  {
    header: "",
    title: "96- العلق",
    description: "",
    id: "096",
  },
  {
    header: "",
    title: "97- القدر",
    description: "",
    id: "097",
  },
  {
    header: "",
    title: "98- البينة",
    description: "",
    id: "098",
  },
  {
    header: "",
    title: "99- الزلزلة",
    description: "",
    id: "099",
  },
  {
    header: "",
    title: "100- العاديات",
    description: "",
    id: "100",
  },
  {
    header: "",
    title: "101- القارعة",
    description: "",
    id: "101",
  },
  {
    header: "",
    title: "102- التكاثر",
    description: "",
    id: "102",
  },
  {
    header: "",
    title: "103- العصر",
    description: "",
    id: "103",
  },
  {
    header: "",
    title: "104- الهمزة",
    description: "",
    id: "104",
  },
  {
    header: "",
    title: "105- الفيل",
    description: "",
    id: "105",
  },
  {
    header: "",
    title: "106- قريش",
    description: "",
    id: "106",
  },
  {
    header: "",
    title: "107- الماعون",
    description: "",
    id: "107",
  },
  {
    header: "",
    title: "108- الكوثر",
    description: "",
    id: "108",
  },
  {
    header: "",
    title: "109- الكافرون",
    description: "",
    id: "109",
  },
  {
    header: "",
    title: "110- النصر",
    description: "",
    id: "110",
  },
  {
    header: "",
    title: "111- المسد",
    description: "",
    id: "111",
  },
  {
    header: "",
    title: "112- الإخلاص",
    description: "",
    id: "112",
  },
  {
    header: "",
    title: "113- الفلق",
    description: "",
    id: "113",
  },
  {
    header: "",
    title: "114- الناس",
    description: "",
    id: "114",
  },
];

export const surahData = {
  "001": { name: "الفاتحة", numberOfAyahs: 7 },
  "002": { name: "البقرة", numberOfAyahs: 286 },
  "003": { name: "آل عمران", numberOfAyahs: 200 },
  "004": { name: "النساء", numberOfAyahs: 176 },
  "005": { name: "المائدة", numberOfAyahs: 120 },
  "006": { name: "الأنعام", numberOfAyahs: 165 },
  "007": { name: "الأعراف", numberOfAyahs: 206 },
  "008": { name: "الأنفال", numberOfAyahs: 75 },
  "009": { name: "التوبة", numberOfAyahs: 129 },
  "010": { name: "يونس", numberOfAyahs: 109 },
  "011": { name: "هود", numberOfAyahs: 123 },
  "012": { name: "يوسف", numberOfAyahs: 111 },
  "013": { name: "الرعد", numberOfAyahs: 43 },
  "014": { name: "إبراهيم", numberOfAyahs: 52 },
  "015": { name: "الحجر", numberOfAyahs: 99 },
  "016": { name: "النحل", numberOfAyahs: 128 },
  "017": { name: "الإسراء", numberOfAyahs: 111 },
  "018": { name: "الكهف", numberOfAyahs: 110 },
  "019": { name: "مريم", numberOfAyahs: 98 },
  "020": { name: "طه", numberOfAyahs: 135 },
  "021": { name: "الأنبياء", numberOfAyahs: 112 },
  "022": { name: "الحج", numberOfAyahs: 78 },
  "023": { name: "المؤمنون", numberOfAyahs: 118 },
  "024": { name: "النور", numberOfAyahs: 64 },
  "025": { name: "الفرقان", numberOfAyahs: 77 },
  "026": { name: "الشعراء", numberOfAyahs: 227 },
  "027": { name: "النمل", numberOfAyahs: 93 },
  "028": { name: "القصص", numberOfAyahs: 88 },
  "029": { name: "العنكبوت", numberOfAyahs: 69 },
  "030": { name: "الروم", numberOfAyahs: 60 },
  "031": { name: "لقمان", numberOfAyahs: 34 },
  "032": { name: "السجدة", numberOfAyahs: 30 },
  "033": { name: "الأحزاب", numberOfAyahs: 73 },
  "034": { name: "سبأ", numberOfAyahs: 54 },
  "035": { name: "فاطر", numberOfAyahs: 45 },
  "036": { name: "يس", numberOfAyahs: 83 },
  "037": { name: "الصافات", numberOfAyahs: 182 },
  "038": { name: "ص", numberOfAyahs: 88 },
  "039": { name: "الزمر", numberOfAyahs: 75 },
  "040": { name: "غافر", numberOfAyahs: 85 },
  "041": { name: "فصلت", numberOfAyahs: 54 },
  "042": { name: "الشورى", numberOfAyahs: 53 },
  "043": { name: "الزخرف", numberOfAyahs: 89 },
  "044": { name: "الدخان", numberOfAyahs: 59 },
  "045": { name: "الجاثية", numberOfAyahs: 37 },
  "046": { name: "الأحقاف", numberOfAyahs: 35 },
  "047": { name: "محمد", numberOfAyahs: 38 },
  "048": { name: "الفتح", numberOfAyahs: 29 },
  "049": { name: "الحجرات", numberOfAyahs: 18 },
  "050": { name: "ق", numberOfAyahs: 45 },
  "051": { name: "الذاريات", numberOfAyahs: 60 },
  "052": { name: "الطور", numberOfAyahs: 49 },
  "053": { name: "النجم", numberOfAyahs: 62 },
  "054": { name: "القمر", numberOfAyahs: 55 },
  "055": { name: "الرحمن", numberOfAyahs: 78 },
  "056": { name: "الواقعة", numberOfAyahs: 96 },
  "057": { name: "الحديد", numberOfAyahs: 29 },
  "058": { name: "المجادلة", numberOfAyahs: 22 },
  "059": { name: "الحشر", numberOfAyahs: 24 },
  "060": { name: "الممتحنة", numberOfAyahs: 13 },
  "061": { name: "الصف", numberOfAyahs: 14 },
  "062": { name: "الجمعة", numberOfAyahs: 11 },
  "063": { name: "المنافقون", numberOfAyahs: 11 },
  "064": { name: "التغابن", numberOfAyahs: 18 },
  "065": { name: "الطلاق", numberOfAyahs: 12 },
  "066": { name: "التحريم", numberOfAyahs: 12 },
  "067": { name: "الملك", numberOfAyahs: 30 },
  "068": { name: "القلم", numberOfAyahs: 52 },
  "069": { name: "الحاقة", numberOfAyahs: 52 },
  "070": { name: "المعارج", numberOfAyahs: 44 },
  "071": { name: "نوح", numberOfAyahs: 28 },
  "072": { name: "الجن", numberOfAyahs: 28 },
  "073": { name: "المزمل", numberOfAyahs: 20 },
  "074": { name: "المدثر", numberOfAyahs: 56 },
  "075": { name: "القيامة", numberOfAyahs: 40 },
  "076": { name: "الإنسان", numberOfAyahs: 31 },
  "077": { name: "المرسلات", numberOfAyahs: 50 },
  "078": { name: "النبأ", numberOfAyahs: 40 },
  "079": { name: "النازعات", numberOfAyahs: 46 },
  "080": { name: "عبس", numberOfAyahs: 42 },
  "081": { name: "التكوير", numberOfAyahs: 29 },
  "082": { name: "الإنفطار", numberOfAyahs: 19 },
  "083": { name: "المطففين", numberOfAyahs: 36 },
  "084": { name: "الإنشقاق", numberOfAyahs: 25 },
  "085": { name: "البروج", numberOfAyahs: 22 },
  "086": { name: "الطارق", numberOfAyahs: 17 },
  "087": { name: "الأعلى", numberOfAyahs: 19 },
  "088": { name: "الغاشية", numberOfAyahs: 26 },
  "089": { name: "الفجر", numberOfAyahs: 30 },
  "090": { name: "البلد", numberOfAyahs: 20 },
  "091": { name: "الشمس", numberOfAyahs: 15 },
  "092": { name: "الليل", numberOfAyahs: 21 },
  "093": { name: "الضحى", numberOfAyahs: 11 },
  "094": { name: "الشرح", numberOfAyahs: 8 },
  "095": { name: "التين", numberOfAyahs: 8 },
  "096": { name: "العلق", numberOfAyahs: 19 },
  "097": { name: "القدر", numberOfAyahs: 5 },
  "098": { name: "البينة", numberOfAyahs: 8 },
  "099": { name: "الزلزلة", numberOfAyahs: 8 },
  100: { name: "العاديات", numberOfAyahs: 11 },
  101: { name: "القارعة", numberOfAyahs: 11 },
  102: { name: "التكاثر", numberOfAyahs: 8 },
  103: { name: "العصر", numberOfAyahs: 3 },
  104: { name: "الهمزة", numberOfAyahs: 9 },
  105: { name: "الفيل", numberOfAyahs: 5 },
  106: { name: "قريش", numberOfAyahs: 4 },
  107: { name: "الماعون", numberOfAyahs: 7 },
  108: { name: "الكوثر", numberOfAyahs: 3 },
  109: { name: "الكافرون", numberOfAyahs: 6 },
  110: { name: "النصر", numberOfAyahs: 3 },
  111: { name: "المسد", numberOfAyahs: 5 },
  112: { name: "الإخلاص", numberOfAyahs: 4 },
  113: { name: "الفلق", numberOfAyahs: 5 },
  114: { name: "الناس", numberOfAyahs: 6 },
};
